name: speakeasy_app_fixed
description: A simple AI Voice Translator
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Permissions
  permission_handler: ^12.0.1

  # Core app
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.3
  http: ^1.6.0

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.3.0

  # Offline ML Kit Translation
  google_mlkit_translation: ^0.13.0

  # Offline storage / caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Connectivity
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/voice_translator.png
    - assets/images/google.png
